# Generated by Django 5.1.7 on 2025-04-04 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizacoes', '0002_autorizacao_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorizacao',
            name='data_hora',
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='autorizacao',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
