# Generated by Django 5.0.1 on 2026-03-10 13:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('turno', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('noturno', 'Noturno'), ('integral', 'Integral')], max_length=20, verbose_name='Turno')),
                ('disciplina', models.CharField(max_length=100, verbose_name='Disciplina')),
                ('professor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Professor')),
                ('sala', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sala')),
                ('horarios', models.JSONField(blank=True, default=dict, verbose_name='Horários')),
                ('dias_letivos', models.JSONField(blank=True, default=list, verbose_name='Dias Letivos')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('concluida', 'Concluída')], default='ativa', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('alunos', models.ManyToManyField(blank=True, related_name='turma_alunos', to='alunos.aluno', verbose_name='Alunos')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['nome'],
                'unique_together': {('nome', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('saida_antecipada', 'Saída Antecipada'), ('ausencia', 'Ausência'), ('atividade_externa', 'Atividade Externa'), ('outro', 'Outro')], max_length=50, verbose_name='Tipo')),
                ('data', models.DateField(verbose_name='Data')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacoes', to='alunos.aluno', verbose_name='Aluno')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacoes', to='turmas.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Autorização',
                'verbose_name_plural': 'Autorizações',
                'ordering': ['-data', '-criado_em'],
            },
        ),
    ]
