# Generated by Django 5.0.1 on 2026-03-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='disciplina',
            field=models.CharField(blank=True, default='Geral', max_length=100, verbose_name='Disciplina'),
        ),
    ]
