# Generated by Django 5.2 on 2025-04-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('turmas', '0002_turma_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='turmas', to='alunos.aluno'),
        ),
    ]
