# Generated by Django 5.0.1 on 2026-03-10 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_alter_turma_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='tipo',
            field=models.CharField(choices=[('base', 'Turma Base'), ('disciplina', 'Turma-Disciplina')], default='base', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='turma',
            name='turma_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turmas_disciplina', to='turmas.turma', verbose_name='Turma Base'),
        ),
    ]
