# Generated by Django 5.0.1 on 2026-03-10 17:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('turmas', '0003_turma_tipo_turma_turma_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AddField(
            model_name='turma',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('prova', 'Prova'), ('trabalho', 'Trabalho'), ('atividade', 'Atividade'), ('projeto', 'Projeto'), ('seminario', 'Seminário'), ('participacao', 'Participação'), ('outro', 'Outro')], default='prova', max_length=50, verbose_name='Tipo')),
                ('data', models.DateField(verbose_name='Data')),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Peso')),
                ('nota_maxima', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Nota Máxima')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='turmas.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Nota')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='alunos.aluno', verbose_name='Aluno')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='turmas.avaliacao', verbose_name='Avaliação')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['aluno__nome'],
                'unique_together': {('avaliacao', 'aluno')},
            },
        ),
    ]
